"""empty message

Revision ID: 5b8be319e3c5
Revises: c100d1146ca4
Create Date: 2022-01-27 20:48:45.959865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b8be319e3c5'
down_revision = 'c100d1146ca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('favourite_type', sa.String(length=15), nullable=True))
    op.drop_column('tracker', 'favorite_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('favorite_type', sa.VARCHAR(length=15), nullable=True))
    op.drop_column('tracker', 'favourite_type')
    # ### end Alembic commands ###
