"""empty message

Revision ID: c100d1146ca4
Revises: bced27214773
Create Date: 2022-01-27 19:39:44.774379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c100d1146ca4'
down_revision = 'bced27214773'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracker', sa.Column('favorite_type', sa.String(length=15), nullable=True))
    op.add_column('tracker', sa.Column('quote_id', sa.String(length=30), nullable=True))
    op.add_column('tracker', sa.Column('date_added', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracker', 'date_added')
    op.drop_column('tracker', 'quote_id')
    op.drop_column('tracker', 'favorite_type')
    # ### end Alembic commands ###
